# -*- coding: utf-8 -*-
"""Vendor Performance and Inventory Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7rXHl3aBFOjd9NkcEJAkKQTJZvQkf5M
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

plt.rcParams['figure.figsize'] = (10,6)
sns.set_style("whitegrid")

sales = pd.read_csv('/content/sales.csv')
vendor_invoice = pd.read_csv('/content/vendor_invoice.csv')
purchases = pd.read_csv('/content/purchases.csv')
purchase_prices = pd.read_csv('/content/purchase_prices.csv')
begin_inventory = pd.read_csv('/content/begin_inventory.csv')
end_inventory = pd.read_csv('/content/end_inventory.csv')

sales.head()

sales.info()

purchases.head()

for df in [sales, purchases, purchase_prices, begin_inventory, end_inventory, vendor_invoice]:
    df.columns = df.columns.str.strip()

sales['SalesDate'] = pd.to_datetime(sales['SalesDate'])

purchase_date_cols = ['PODate', 'ReceivingDate', 'InvoiceDate', 'PayDate']
for col in purchase_date_cols:
    purchases[col] = pd.to_datetime(purchases[col])

sales.head()

purchases.head()

sales['Revenue'] = sales['SalesQuantity'] * sales['SalesPrice']

sales = sales.merge(
    purchase_prices[['Brand', 'PurchasePrice']],
    on='Brand',
    how='left'
)

sales['Cost'] = sales['SalesQuantity'] * sales['PurchasePrice']
sales['Profit'] = sales['Revenue'] - sales['Cost']
sales['ProfitMargin'] = (sales['Profit'] / sales['Revenue']) * 100

brand_perf = sales.groupby('Brand').agg({
    'Revenue': 'sum',
    'Profit': 'sum',
    'ProfitMargin': 'mean'
}).reset_index()

brand_perf.sort_values('Profit').head(10)

sns.barplot(
    data=brand_perf.sort_values('Profit').head(10),
    x='Profit',
    y='Brand'
)
plt.title('Underperforming Brands')
plt.show()

vendor_perf = sales.groupby('VendorName').agg({
    'Revenue': 'sum',
    'Profit': 'sum'
}).reset_index()

vendor_perf.sort_values('Profit', ascending=False).head(10)

sns.barplot(
    data=vendor_perf.sort_values('Profit', ascending=False).head(10),
    x='Profit',
    y='VendorName'
)
plt.title('Top Vendors by Profit')
plt.show()

bulk_purchase = purchases.groupby('Brand').agg({
    'Quantity': 'sum',
    'PurchasePrice': 'mean'
}).reset_index()

sns.scatterplot(
    data=bulk_purchase,
    x='Quantity',
    y='PurchasePrice'
)
plt.title('Bulk Purchase Quantity vs Unit Cost')
plt.xlabel('Total Quantity Purchased')
plt.ylabel('Average Purchase Price')
plt.show()

begin_inventory.columns

end_inventory.columns

inventory = begin_inventory.merge(
    end_inventory,
    on=['InventoryId', 'Store', 'Brand'],
    suffixes=('_begin', '_end')
)

inventory['AverageInventory'] = (
    inventory['onHand_begin'] + inventory['onHand_end']
) / 2

sales_qty = sales.groupby('Brand')['SalesQuantity'].sum().reset_index()

inventory_turnover = sales_qty.merge(
    inventory[['Brand', 'AverageInventory']],
    on='Brand',
    how='left'
)

inventory_turnover['InventoryTurnover'] = (
    inventory_turnover['SalesQuantity'] /
    inventory_turnover['AverageInventory']
)

inventory_turnover.sort_values('InventoryTurnover').head(10)

"""STEP 5: VENDOR SCORECARD (CORE BUSINESS OUTPUT)"""

sales.columns

vendor_scorecard = sales.groupby(
    'VendorName'
).agg(
    Total_Sales_Qty=('SalesQuantity', 'sum'),
    Total_Revenue=('Revenue', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Avg_Profit_Margin=('ProfitMargin', 'mean')
).reset_index()

vendor_scorecard.head()

vendor_scorecard['Profit_Rank'] = vendor_scorecard['Total_Profit'].rank(ascending=False)

vendor_scorecard.sort_values('Profit_Rank').head(10)

"""🧩 STEP 6: VENDOR SEGMENTATION (HIGH / MEDIUM / LOW)"""

vendor_scorecard['Total_Profit'].describe()

low_cut = vendor_scorecard['Total_Profit'].quantile(0.30)
high_cut = vendor_scorecard['Total_Profit'].quantile(0.70)

def segment_vendor(profit):
    if profit >= high_cut:
        return 'High Performing'
    elif profit >= low_cut:
        return 'Medium Performing'
    else:
        return 'Low Performing'

vendor_scorecard['Vendor_Category'] = vendor_scorecard['Total_Profit'].apply(segment_vendor)

vendor_scorecard['Vendor_Category'].value_counts()

sns.countplot(
    data=vendor_scorecard,
    x='Vendor_Category',
    order=['High Performing', 'Medium Performing', 'Low Performing']
)
plt.title('Vendor Segmentation Based on Profit')
plt.xlabel('Vendor Category')
plt.ylabel('Number of Vendors')
plt.show()

"""📊 STEP 7: MANAGEMENT INSIGHTS"""

vendor_scorecard.sort_values('Total_Profit', ascending=False).head(10)

vendor_scorecard.sort_values('Total_Profit').head(10)

"""STEP 8: FINAL KPI SUMMARY (FOR DASHBOARD)"""

total_revenue = vendor_scorecard['Total_Revenue'].sum()
total_profit = vendor_scorecard['Total_Profit'].sum()
total_vendors = vendor_scorecard.shape[0]

print("Total Revenue:", total_revenue)
print("Total Profit:", total_profit)
print("Total Vendors:", total_vendors)

vendor_scorecard.to_csv('vendor_scorecard_final.csv', index=False)
inventory_turnover.to_csv('inventory_turnover_final.csv', index=False)
brand_perf.to_csv('brand_performance_final.csv', index=False)

